name: Deploy to GitHub Pages (gh-pages branch)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # if your site is already in the repo root on main (index.html, assets, etc.)
      # this publishes the repo contents as-is.
      - name: Add .nojekyll
        run: touch .nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
          force_orphan: true
